config/routes.rb
Rails.application.routes.draw do
  root  'sports#index'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  post '/logout', to: 'sessions#destroy'
  post '/favorites/:id', to: 'favorites#create', as: 'new_favorite'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


  resources :teams, only: [:show]
  resources :players, only: [:show, :index]
  resources :sports, only: [:index, :show]
  resources :users, except: [:index]
  resources :favorites, only: [:destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user
    belongs_to :player
end

app/models/player.rb
class Player < ApplicationRecord
    belongs_to :team
    has_many :favorites
    has_many :users, through: :favorites


    def full_name
        "#{first_name} #{last_name}"
    end

    def self.search(search)
        if search
            players = Player.where("lower(first_name) = ?", search.downcase)
                if !players.empty?
                    players
                else
                    Player.all
                end
            else
                Player.all
        end
    end



end

app/models/sport.rb
class Sport < ApplicationRecord
    has_many :teams
end

app/models/team.rb
class Team < ApplicationRecord
    has_many :players
    belongs_to :sport
end

app/models/user.rb
class User < ApplicationRecord
    has_many :favorites
    has_many :players, through: :favorites
    validates :name, :user_name, presence: true
    validates :user_name, uniqueness: true
    has_secure_password

    before_save :set_default_image

    def set_default_image
        self.profile_pic = "aerial-view-of-soccer-field-1171084.jpg" if profile_pic.nil?
    end

    


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :logged_in?, :current_user

    def user_log_in(user_id)
        session[:user_id] = user_id
    end

    def current_user
        if logged_in?
            @user = User.find(session[:user_id])
        else
            redirect_to '/'
        end
    end

    def logged_in?
        !!session[:user_id]
    end



end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
    before_action :set_player

    def create
        # byebug
        @user = current_user
        @fav = Favorite.new(user_id: @user.id, player_id: @player.id)
        # byebug
        if @fav.save
            redirect_to player_path(@player)
        else
            redirect_to player_path(@player), alert: "Oopsies!"
        end
    end

    def destroy
        @fav = Favorite.find_by(id: params[:id])
        @fav.destroy
        @player = Player.find_by(id: @fav.player_id)
        redirect_to player_path(@player)
    end



    private
    
    def set_player
        @player = Player.find_by(id: params[:id])
    end


end

app/controllers/players_controller.rb
class PlayersController < ApplicationController

    def index
        current_user
        @players = Player.search(params[:search])
    end


    def show
        current_user
        @player = Player.find(params[:id])
    end




    private

    def player_params
        params.require(:player).permit(:first_name, :last_name, :search)
    end

    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    # byebug
    return head(:forbidden) unless logged_in? == false
    @user = User.new
    # byebug
  end

  def create
    @user = User.find_by(user_name: params[:user_name])
    if @user && @user.authenticate(params[:password])
       user_log_in(@user.id)
       redirect_to user_path(@user)
    else
      return head(:forbidden)
    end
  end

  def destroy
    session.delete :user_id

    redirect_to '/'
  end



end

app/controllers/sports_controller.rb
class SportsController < ApplicationController
    

    def index
        @sports = Sport.all
    end

    def show
        if logged_in?
            @sport = Sport.find(params[:id])
        else
            redirect_to '/'
        end
    end




end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController

    def show
        current_user
        @team = Team.find(params[:id])
    end





end

app/controllers/users_controller.rb
class UsersController < ApplicationController



    def show
        current_user
    end

    def new
        return head(:forbidden) unless logged_in? == false
            @user = User.new
    end

    def create
        @user = User.new(user_params)
            if @user.save
                user_log_in(@user.id)
                    redirect_to user_path(@user)
                else
                    render 'new'
                end
    end

    def edit
        current_user
    end

    def update
        current_user
        if current_user.update(user_params)
            redirect_to user_path(current_user)
        else
            render 'edit'
        end
    end

     def destroy
    current_user.destroy
    session.delete :user_id
    redirect_to new_user_path
     end

    






    private


    def user_params
        params.require(:user).permit(:name, :user_name, :bio, :profile_pic, :password, :password_confirmation)
    end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/sports_helper.rb
module SportsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mod2Project</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <style>

</style>
<div id='header'>
<ul>
  <li><%= link_to 'Homepage', '/', method: :get %></li>
  <% if !logged_in? %>
  <li><%= link_to 'User Login', login_path %></li>
  <li><%= link_to 'Create Account', new_user_path(controller: 'user', action: 'new') %></li>
  <% else %>
  <li><%= link_to 'Logout', logout_path, method: :post %></li>
  <li><%= link_to 'Edit Profile', edit_user_path(current_user), method: :get %></li>
  <li><%= link_to 'Profile Page', user_path(current_user), method: :get %></li>
  <li><%= link_to 'Delete Account', user_path(current_user), method: :delete  %></li>
  <li><%= link_to 'Player search', players_path, method: :get %></li>
  <% end %>
</ul>
</div>
    <%= yield %>
  </body>
</html>

app/views/players/index.html.erb
<h3>Player Search!</h3>
<style>
body {
  background-color: lightgray;
}
</style>




<%= form_tag players_path, method: :get do %>
<h3><%= label_tag(:search, "Which Player are you looking for?") %></h3>
<%= text_field_tag :search, params[:search]  %>
<%= submit_tag('Search') %>
<% end %>

<% @players.each do |player| %>
    <ul class='index_players'>
        <li><%= link_to player.full_name, player_path(player) %></li><br>
    </ul>
<% end %>

app/views/players/show.html.erb
<body class='player_nba'>
<h1 class='teams'><%= @player.full_name %></h1> 

<p class='teams'>Jersey Number #<%= @player.jersey_number %></p><br>

<p class='teams'><%= @player.position %></p>
<p class='teams'>Weight: <%= @player.weight_pounds %> Lbs</p><br>
<p class='teams'>Nationality: <%= @player.nationality %></p><br>
<p class='teams'>College: <%= @player.university %></p>
<% @fav = @user.favorites.find_by(player_id: @player.id)   %>
<% if @fav %>
<%= button_to 'Unfavorite', favorite_path(@fav), method: :delete %>
<% else %>
<%= button_to 'Favorite', new_favorite_path(@player) %>
<% end %>




<h3 class='teams'>Career Stat Averages:</h3>

<style>
table, th, td {
  border: 1px solid gray;
  border-collapse: collapse;
}
th, td {
  padding: 5px;
}
th {
  text-align: left;
}
</style>

    <table style="width:80%" class='teams'>
        <tr>
            <th>Points per game</th>
            <th>Assists per game</th>
            <th>Rebounds per game</th>
            <th>Steals per game</th>
            <th>Turnovers per game</th>
            <th>Fouls per game</th>
            <th>Minutes per game</th>
        </tr>
        <tr>
            <td><%= @player.ppg.round(2) %></td>
            <td><%= @player.apg.round(2) %></td>
            <td><%= @player.rpg.round(2) %></td>
            <td><%= @player.spg.round(2) %></td>
            <td><%= @player.tpg.round(2) %></td>
            <td><%= @player.fpg.round(2) %></td>
            <td><%= @player.mpg.round(2) %></td>
            </tr>    
    </table>
    </body>

app/views/sports/index.html.erb
<body class="sports">    

<h1 style="font-family:verdana; color:coral; font-size:300%; text-align:center">#Life'sTooSport!</h1>

<div class='logo'>
<% @sports.uniq.each do |sport| %>


    <% if sport.name == 'NBA'  %>
        <%= link_to image_tag("https://cdn.freebiesupply.com/images/large/2x/nba-logo-transparent.png",  size: "325"), sport_path(sport), method: :get %>
    <% end%>
    <% if sport.name == 'NFL'  %>
        <%= link_to image_tag("https://cdn.freebiesupply.com/logos/large/2x/nfl-1-logo-png-transparent.png",  size: "325"), sport_path(sport), method: :get %>
    <% end%>
    <% if sport.name == 'MLB'  %>
        <%= link_to image_tag("https://cdn.bleacherreport.net/images/team_logos/328x328/mlb_highlights.png",  size: "325"), sport_path(sport), method: :get %>
    <% end%>
        
<% end %>
</div>





</body>
</html>

app/views/sports/show.html.erb
<body class='nba'>

<h1 class='sportName'><%= @sport.name %></h1>

<%# <div class="background_image">
<%= image_tag(@sport.background_image) %>
<%# </div>  %>

<ul class='teams'>
<% @sport.teams.each do |team| %>
 <li class='name'><%= link_to team.full_name, team_path(team) %></li>
 <% end %>
 </ul>

</body>

app/views/users/edit.html.erb
<h2>Edit:</h2>

<%= form_for @user do |f| %><br>
<%= f.label :username %>
<%= f.text_field :user_name %><br><br>
<%= f.label :profile_picture %>
<%= f.text_field :profile_pic %><br><br>
<%= f.label :bio %>
<%= f.text_area :bio %><br><br>
<%= f.label :password %>
<%= f.password_field :password %><br>
<%= f.label :password_confirmation %>
<%= f.password_field :password_confirmation%><br><br>
<%= f.submit 'Update info' %>
<% end %>

app/views/users/new.html.erb
<h1><em>Welcome! Create New Fanatic Here:</em></h1>

<%= form_for @user do |f| %>
<%= f.label :name %>
<%= f.text_field :name %><br>
<%= f.label :user_name %>
<%= f.text_field :user_name %><br>
<%= f.label :password %>
<%= f.password_field :password %><br>
<%= f.label :password_confirmation %>
<%= f.password_field :password_confirmation%><br><br>
<%= f.submit 'Create!' %>
<% end %>

app/views/users/show.html.erb
<style>
body {
        background-image: url("https://images.pexels.com/photos/1939485/pexels-photo-1939485.jpeg?cs=srgb&dl=white-painted-wall-1939485.jpg&fm=jpg");
        background-size: cover;
        background-attachment: fixed;
        background-repeat: no-repeat; 
    }
</style>


<h2><%= @user.user_name %></h2>

<div class="profile_image">
<%= image_tag(@user.profile_pic)%>
</div>

<h3>Bio:</h3>
<h4><%= @user.bio %></h4><br><br><br>

<% if !@user.favorites.empty? %>
<h1>Favorited Players:</h1>
<% else %>
<h1>No Favorited Players</h2>
<% end %>
<hr/>
<% if @user.players %>
<% @user.players.each do |player| %>
<h2 style='text-align: center'><%= player.full_name %> <%= player.position %> - <%= player.team.full_name %></h2>
<h3>Career Stat Averages:</h3>

<% @fav = @user.favorites.find_by(player_id: player.id) %>
<%= button_to 'Unfavorite', favorite_path(@fav), method: :delete %>






<style>
table, th, td {
  border: 1px solid black;
  border-collapse: collapse;
}
th, td {
  padding: 5px;
}
th {
  text-align: left;
}
</style>

    <table style="width:80%">
        <tr>
            <th>Points per game</th>
            <th>Assists per game</th>
            <th>Rebounds per game</th>
            <th>Steals per game</th>
            <th>Turnovers per game</th>
            <th>Fouls per game</th>
            <th>Minutes per game</th>
        </tr>
        <tr>
            <td><%= player.ppg.round(2) %></td>
            <td><%= player.apg.round(2) %></td>
            <td><%= player.rpg.round(2) %></td>
            <td><%= player.spg.round(2) %></td>
            <td><%= player.tpg.round(2) %></td>
            <td><%= player.fpg.round(2) %></td>
            <td><%= player.mpg.round(2) %></td>
            </tr>    
    </table>
<hr/>
<% end  %>
<% end %>